TABLE_LEAGUES, TABLE_FIXTURES, TABLE_ODDS, TABLE_RESULTS, TABLE_BETS, TABLE_USERS = 'leagues', 'fixtures', 'odds', 'results', 'bets', 'users'

TEXT_LANDING_PAGE = """

## **TRACK-A-BET. Track your bets efficiently.**

For a quick start I recommend watching this 3-part series

#1 Getting Started https://youtu.be/j-J3AL2UFK0

#2 Editing & deleting a bet https://youtu.be/jzxRzTnCjCQ

#3 What do all these values mean? https://youtu.be/s-aOSVbuFao

#### THIS TOOL WILL REVEAL YOUR EDGE. INSTANTLY.

👉 Log your bets and keep track of profits + clv (closing line value) with this easy-to-use app.

👉 Backtest your models, strategies and your favourite tipsters with a database dating back to 2021.

👉 Add future bets and retrieve current odds, expected win & clv, so you know exactly where you currently stand with your bet. Updated every minute.

👉 Automatic grading of your bets, including scorelines.

👉 RATING from A - F measuring the quality of your bets.

👉 LUCK FACTOR from -3 to +3 giving you an idea of how lucky/unlucky you were with the results of your bets.

👉 41 unique sports, 15159 unique leagues supported.

👉 1.5 million fixtures and growing.

👉 Fulltime, halftime, quarter markets supported and many more.

👉 moneyline, spread, totals & team_totals supported.

👉 Export option allows you to download and share your bets.

👉 Clean & simple, no-nonsense interface & interactive dashboard.

👉 Precise clv calculation using [@12Xpert](https://twitter.com/12Xpert?lang=en) 's logarithmic function, explained in his article here https://tinyurl.com/woc12Xpert

👉 Tag your bets and apply it as a filter for future analysis.

👉 Performance graph showing actual vs expected profits.

👉 Do not get fooled by randomness ever again. Use clv as the ultimate predictor of your profitability.

#### ⚠️ WHAT THIS TOOL CAN NOT DO ⚠️
It can not track special bets. Hence if you're mainly betting prop markets & exotic derivatives then this tool is not for you.

#### ❓ WHY WOULD I WANT YET ANOTHER BET TRACKER ❓
**Because it calculates your clv/edge accurately. Probably THE most important thing to know if you want to be a long-term winner.**

A basic requirement to profitable betting is to log your bets. At a bare minimum you want to log EVERY BET and know your overall P/L + ROI for each strategy/model you follow.

You can then apply all sorts of metrics to your sample (such as ROI, P-VALUE). However many of them won't be very helpful to make any meaningful conclusions!

Most of the commonly used metrics will suffer from small sample sizes and/or Survivorship Bias as discussed in this article here https://tinyurl.com/illusionofskill 

Worst case is that you end up with a false positive, i.e. the illusion that you have an edge when in fact you have none.

**WHAT YOU WANT IS A CLEAR SIGNAL. A metric that tells you if and what edge you have over any particular market.**

Enter CLV. Closing Line Value.

#### ❓ WHAT IS CLV AND WHY IS IT SO IMPORTANT TO UNDERSTAND ❓

In a nutshell clv compares the odds you take against the true closing odds. The true closing odds are the odds just before kickoff with the bookmaker margin removed. Since the true closing odds reflect the true probability of an outcome quite accuratey, you will know instantly if you have made a value bet or not.

For the math-savvy, here is the formula.

clv = o / t - 1

where

o...are the obtained odds, i.e. the price you took at your book

t...the true closing price, a.k.a. the no-vig closing price

This means IF THE OBTAINED PRICE IS HIGHER THAN THE NO-VIG CLOSING PRICE YOU MADE A VALUE BET!

**IN OTHER WORDS: NO CLV = NO EDGE!**

Understanding closing line value (= clv) is absolutely vital for aspiring sports bettors. As soon as you get a grasp on this metric you will think completely differently (and properly!) about your bet.

All of a sudden the outcome becomes irrelevant!

If you take a bet at 3.5 and it closes at 2.8. Happy Days. Regardless of whether the bet wins or not.

That's how professional bettors think!

[@nishikoripicks](https://twitter.com/nishikoripicks?lang=en) nails it with his 2-part video!

Part I: https://youtube.com/watch?v=-uLJUhbFD_U

Part II: https://youtube.com/watch?v=MZCeHiywKvs

Another thing of beauty is that you do not need a very large sample if analysing for clv. Usually 50 - 100 bets will suffice to get a good idea where you are heading. Hence if your clv is +2.50% over 100 bets then you can be pretty confident that this is approximately your expected roi.

"""


SPORTS = dict()
SPORTS.update({'Soccer': 29})
SPORTS.update({'Basketball': 4})
SPORTS.update({'Tennis': 33})
SPORTS.update({'Baseball': 3})
SPORTS.update({'Football': 15})
SPORTS.update({'Hockey': 19})
SPORTS.update({'Rugby League': 26})
SPORTS.update({'Rugby Union': 27})
SPORTS.update({'Darts': 10})
SPORTS.update({'Cricket': 8})
SPORTS.update({'Golf': 17})
SPORTS.update({'Handball': 18})
SPORTS.update({'Snooker': 28})
SPORTS.update({'Volleyball': 34})
SPORTS.update({'Aussie Rules': 39})
SPORTS.update({'Alpine Skiing': 40})
SPORTS.update({'Athletics': 56})
SPORTS.update({'Badminton': 1})
SPORTS.update({'Bandy': 2})
SPORTS.update({'Beach Volleyball': 5})
SPORTS.update({'Biathlon': 41})
SPORTS.update({'Boxing': 6})
SPORTS.update({'Chess': 7})
SPORTS.update({'Cross Country': 43})
SPORTS.update({'Crossfit': 57})
SPORTS.update({'Curling': 9})
SPORTS.update({'Cycling': 45})
SPORTS.update({'Entertainment': 58})
SPORTS.update({'Field Hockey': 13})
SPORTS.update({'Formula 1': 44})
SPORTS.update({'Futsal': 16})
SPORTS.update({'Mixed Martial Arts': 22})
SPORTS.update({'Motorsport': 63})
SPORTS.update({'Olympics': 55})
SPORTS.update({'Padel Tennis': 37})
SPORTS.update({'Ski Jumping': 42})
SPORTS.update({'Softball': 30})
SPORTS.update({'Squash': 31})
SPORTS.update({'Sumo': 65})
SPORTS.update({'Table Tennis': 32})
SPORTS.update({'Water Polo': 36})

PERIODS = dict()
PERIODS.update({(29,0): 'Match'})
PERIODS.update({(29,1): '1st Half'})
PERIODS.update({(29,2): '2nd Half'})
PERIODS.update({(29,3): 'Extra Time'})
PERIODS.update({(29,4): 'Extra Time 1st Half'})
PERIODS.update({(29,5): 'Extra Time 2nd Half'})
PERIODS.update({(29,6): 'Penalty Shootout'})
PERIODS.update({(29,7): '1st Ten Shootout Pen'})
PERIODS.update({(29,8): 'To Qualify'})
PERIODS.update({(29,9): '00:00 - 04:59'})
PERIODS.update({(29,10): '05:00 - 09:59'})
PERIODS.update({(29,11): '10:00 - 14:59'})
PERIODS.update({(29,12): '15:00 - 19:59'})
PERIODS.update({(29,13): '20:00 - 24:59'})
PERIODS.update({(29,14): '25:00 - 29:59'})
PERIODS.update({(29,15): '30:00 - 34:59'})
PERIODS.update({(29,16): '35:00 - 39:59'})
PERIODS.update({(29,17): '40:00 - 44:59'})
PERIODS.update({(29,18): 'Halftime - 49:59'})
PERIODS.update({(29,19): '50:00 - 54:59'})
PERIODS.update({(29,20): '55:00 - 59:59'})
PERIODS.update({(29,21): '60:00 - 64:59'})
PERIODS.update({(29,22): '65:00 - 69:59'})
PERIODS.update({(29,23): '70:00 - 74:59'})
PERIODS.update({(29,24): '75:00 - 79:59'})
PERIODS.update({(29,25): '80:00 - 84:59'})
PERIODS.update({(29,26): '85:00 - 89:59'})
PERIODS.update({(29,27): 'ET 00:00 - 04:59'})
PERIODS.update({(29,28): 'ET 05:00 - 09:59'})
PERIODS.update({(29,29): 'ET 10:00 - 14:59'})
PERIODS.update({(29,30): 'ET Halftime - 19:59'})
PERIODS.update({(29,31): 'ET 20:00 - 24:59'})
PERIODS.update({(29,32): 'ET 25:00 - 29:59'})
PERIODS.update({(29,33): '00:00 - 14:59'})
PERIODS.update({(29,34): '15:00 - 29:59'})
PERIODS.update({(29,35): '30:00 - Halftime'})
PERIODS.update({(29,36): 'Halftime - 59:59'})
PERIODS.update({(29,37): '60:00 - 74:59'})
PERIODS.update({(29,38): '75:00 - Fulltime'})
PERIODS.update({(29,39): 'To Win Final'})
PERIODS.update({(4,0): 'Game'})
PERIODS.update({(4,1): '1st Half'})
PERIODS.update({(4,2): '2nd Half'})
PERIODS.update({(4,3): '1st Quarter'})
PERIODS.update({(4,4): '2nd Quarter'})
PERIODS.update({(4,5): '3rd Quarter'})
PERIODS.update({(4,6): '4th Quarter'})
PERIODS.update({(33,0): 'Match'})
PERIODS.update({(33,1): '1st Set'})
PERIODS.update({(33,2): '2nd Set'})
PERIODS.update({(33,3): '3rd Set'})
PERIODS.update({(33,4): '4th Set'})
PERIODS.update({(33,5): '5th Set'})
PERIODS.update({(33,6): 'Set 1 Game 1'})
PERIODS.update({(33,7): 'Set 1 Game 2'})
PERIODS.update({(33,8): 'Set 1 Game 3'})
PERIODS.update({(33,9): 'Set 1 Game 4'})
PERIODS.update({(33,10): 'Set 1 Game 5'})
PERIODS.update({(33,11): 'Set 1 Game 6'})
PERIODS.update({(33,12): 'Set 1 Game 7'})
PERIODS.update({(33,13): 'Set 1 Game 8'})
PERIODS.update({(33,14): 'Set 1 Game 9'})
PERIODS.update({(33,15): 'Set 1 Game 10'})
PERIODS.update({(33,16): 'Set 1 Game 11'})
PERIODS.update({(33,17): 'Set 1 Game 12'})
PERIODS.update({(33,18): 'Set 1 Game 13'})
PERIODS.update({(33,19): 'Set 2 Game 1'})
PERIODS.update({(33,20): 'Set 2 Game 2'})
PERIODS.update({(33,21): 'Set 2 Game 3'})
PERIODS.update({(33,22): 'Set 2 Game 4'})
PERIODS.update({(33,23): 'Set 2 Game 5'})
PERIODS.update({(33,24): 'Set 2 Game 6'})
PERIODS.update({(33,25): 'Set 2 Game 7'})
PERIODS.update({(33,26): 'Set 2 Game 8'})
PERIODS.update({(33,27): 'Set 2 Game 9'})
PERIODS.update({(33,28): 'Set 2 Game 10'})
PERIODS.update({(33,29): 'Set 2 Game 11'})
PERIODS.update({(33,30): 'Set 2 Game 12'})
PERIODS.update({(33,31): 'Set 2 Game 13'})
PERIODS.update({(33,32): 'Set 3 Game 1'})
PERIODS.update({(33,33): 'Set 3 Game 2'})
PERIODS.update({(33,34): 'Set 3 Game 3'})
PERIODS.update({(33,35): 'Set 3 Game 4'})
PERIODS.update({(33,36): 'Set 3 Game 5'})
PERIODS.update({(33,37): 'Set 3 Game 6'})
PERIODS.update({(33,38): 'Set 3 Game 7'})
PERIODS.update({(33,39): 'Set 3 Game 8'})
PERIODS.update({(33,40): 'Set 3 Game 9'})
PERIODS.update({(33,41): 'Set 3 Game 10'})
PERIODS.update({(33,42): 'Set 3 Game 11'})
PERIODS.update({(33,43): 'Set 3 Game 12'})
PERIODS.update({(33,44): 'Set 3 Game 13'})
PERIODS.update({(33,45): 'Set 3 Game 14'})
PERIODS.update({(33,46): 'Set 3 Game 15'})
PERIODS.update({(33,47): 'Set 3 Game 16'})
PERIODS.update({(33,48): 'Set 3 Game 17'})
PERIODS.update({(33,49): 'Set 3 Game 18'})
PERIODS.update({(33,50): 'Set 3 Game 19'})
PERIODS.update({(33,51): 'Set 3 Game 20'})
PERIODS.update({(33,52): 'Set 3 Game 21'})
PERIODS.update({(33,53): 'Set 3 Game 22'})
PERIODS.update({(33,54): 'Set 3 Game 23'})
PERIODS.update({(33,55): 'Set 3 Game 24'})
PERIODS.update({(33,56): 'Set 3 Game 25'})
PERIODS.update({(33,57): 'Set 3 Game 26'})
PERIODS.update({(33,58): 'Set 3 Game 27'})
PERIODS.update({(33,59): 'Set 3 Game 28'})
PERIODS.update({(33,60): 'Set 3 Game 29'})
PERIODS.update({(33,61): 'Set 3 Game 30'})
PERIODS.update({(33,62): 'Set 3 Game 31'})
PERIODS.update({(33,63): 'Set 3 Game 32'})
PERIODS.update({(33,64): 'Set 3 Game 33'})
PERIODS.update({(33,65): 'Set 3 Game 34'})
PERIODS.update({(33,66): 'Set 3 Game 35'})
PERIODS.update({(33,67): 'Set 3 Game 36'})
PERIODS.update({(33,68): 'Set 3 Game 37'})
PERIODS.update({(33,69): 'Set 3 Game 38'})
PERIODS.update({(33,70): 'Set 3 Game 39'})
PERIODS.update({(33,71): 'Set 3 Game 40'})
PERIODS.update({(33,72): 'Set 3 Game 41'})
PERIODS.update({(33,73): 'Set 3 Game 42'})
PERIODS.update({(33,74): 'Set 3 Game 43'})
PERIODS.update({(33,75): 'Set 3 Game 44'})
PERIODS.update({(33,76): 'Set 3 Game 45'})
PERIODS.update({(33,77): 'Set 3 Game 46'})
PERIODS.update({(33,78): 'Set 3 Game 47'})
PERIODS.update({(33,79): 'Set 3 Game 48'})
PERIODS.update({(33,80): 'Set 3 Game 49'})
PERIODS.update({(33,81): 'Set 3 Game 50'})
PERIODS.update({(33,82): 'Set 3 Game 51'})
PERIODS.update({(33,83): 'Set 3 Game 52'})
PERIODS.update({(33,84): 'Set 3 Game 53'})
PERIODS.update({(33,85): 'Set 3 Game 54'})
PERIODS.update({(33,86): 'Set 3 Game 55'})
PERIODS.update({(33,87): 'Set 3 Game 56'})
PERIODS.update({(33,88): 'Set 3 Game 57'})
PERIODS.update({(33,89): 'Set 3 Game 58'})
PERIODS.update({(33,90): 'Set 3 Game 59'})
PERIODS.update({(33,91): 'Set 3 Game 60'})
PERIODS.update({(33,92): 'Set 3 Game 61'})
PERIODS.update({(33,93): 'Set 3 Game 62'})
PERIODS.update({(33,94): 'Set 3 Game 63'})
PERIODS.update({(33,95): 'Set 3 Game 64'})
PERIODS.update({(33,96): 'Set 3 Game 65'})
PERIODS.update({(33,97): 'Set 3 Game 66'})
PERIODS.update({(33,98): 'Set 3 Game 67'})
PERIODS.update({(33,99): 'Set 3 Game 68'})
PERIODS.update({(33,100): 'Set 3 Game 69'})
PERIODS.update({(33,101): 'Set 3 Game 70'})
PERIODS.update({(33,102): 'Set 3 Game 71'})
PERIODS.update({(33,103): 'Set 3 Game 72'})
PERIODS.update({(33,104): 'Set 3 Game 73'})
PERIODS.update({(33,105): 'Set 3 Game 74'})
PERIODS.update({(33,106): 'Set 3 Game 75'})
PERIODS.update({(33,107): 'Set 3 Game 76'})
PERIODS.update({(33,108): 'Set 3 Game 77'})
PERIODS.update({(33,109): 'Set 3 Game 78'})
PERIODS.update({(33,110): 'Set 3 Game 79'})
PERIODS.update({(33,111): 'Set 3 Game 80'})
PERIODS.update({(33,112): 'Set 3 Game 81'})
PERIODS.update({(33,113): 'Set 3 Game 82'})
PERIODS.update({(33,114): 'Set 3 Game 83'})
PERIODS.update({(33,115): 'Set 3 Game 84'})
PERIODS.update({(33,116): 'Set 3 Game 85'})
PERIODS.update({(33,117): 'Set 3 Game 86'})
PERIODS.update({(33,118): 'Set 3 Game 87'})
PERIODS.update({(33,119): 'Set 3 Game 88'})
PERIODS.update({(33,120): 'Set 3 Game 89'})
PERIODS.update({(33,121): 'Set 3 Game 90'})
PERIODS.update({(33,122): 'Set 3 Game 91'})
PERIODS.update({(33,123): 'Set 3 Game 92'})
PERIODS.update({(33,124): 'Set 3 Game 93'})
PERIODS.update({(33,125): 'Set 3 Game 94'})
PERIODS.update({(33,126): 'Set 3 Game 95'})
PERIODS.update({(33,127): 'Set 3 Game 96'})
PERIODS.update({(33,128): 'Set 3 Game 97'})
PERIODS.update({(33,129): 'Set 3 Game 98'})
PERIODS.update({(33,130): 'Set 3 Game 99'})
PERIODS.update({(33,131): 'Set 3 Game 100'})
PERIODS.update({(33,132): 'Set 4 Game 1'})
PERIODS.update({(33,133): 'Set 4 Game 2'})
PERIODS.update({(33,134): 'Set 4 Game 3'})
PERIODS.update({(33,135): 'Set 4 Game 4'})
PERIODS.update({(33,136): 'Set 4 Game 5'})
PERIODS.update({(33,137): 'Set 4 Game 6'})
PERIODS.update({(33,138): 'Set 4 Game 7'})
PERIODS.update({(33,139): 'Set 4 Game 8'})
PERIODS.update({(33,140): 'Set 4 Game 9'})
PERIODS.update({(33,141): 'Set 4 Game 10'})
PERIODS.update({(33,142): 'Set 4 Game 11'})
PERIODS.update({(33,143): 'Set 4 Game 12'})
PERIODS.update({(33,144): 'Set 4 Game 13'})
PERIODS.update({(33,145): 'Set 5 Game 1'})
PERIODS.update({(33,146): 'Set 5 Game 2'})
PERIODS.update({(33,147): 'Set 5 Game 3'})
PERIODS.update({(33,148): 'Set 5 Game 4'})
PERIODS.update({(33,149): 'Set 5 Game 5'})
PERIODS.update({(33,150): 'Set 5 Game 6'})
PERIODS.update({(33,151): 'Set 5 Game 7'})
PERIODS.update({(33,152): 'Set 5 Game 8'})
PERIODS.update({(33,153): 'Set 5 Game 9'})
PERIODS.update({(33,154): 'Set 5 Game 10'})
PERIODS.update({(33,155): 'Set 5 Game 11'})
PERIODS.update({(33,156): 'Set 5 Game 12'})
PERIODS.update({(33,157): 'Set 5 Game 13'})
PERIODS.update({(33,158): 'Set 5 Game 14'})
PERIODS.update({(33,159): 'Set 5 Game 15'})
PERIODS.update({(33,160): 'Set 5 Game 16'})
PERIODS.update({(33,161): 'Set 5 Game 17'})
PERIODS.update({(33,162): 'Set 5 Game 18'})
PERIODS.update({(33,163): 'Set 5 Game 19'})
PERIODS.update({(33,164): 'Set 5 Game 20'})
PERIODS.update({(33,165): 'Set 5 Game 21'})
PERIODS.update({(33,166): 'Set 5 Game 22'})
PERIODS.update({(33,167): 'Set 5 Game 23'})
PERIODS.update({(33,168): 'Set 5 Game 24'})
PERIODS.update({(33,169): 'Set 5 Game 25'})
PERIODS.update({(33,170): 'Set 5 Game 26'})
PERIODS.update({(33,171): 'Set 5 Game 27'})
PERIODS.update({(33,172): 'Set 5 Game 28'})
PERIODS.update({(33,173): 'Set 5 Game 29'})
PERIODS.update({(33,174): 'Set 5 Game 30'})
PERIODS.update({(33,175): 'Set 5 Game 31'})
PERIODS.update({(33,176): 'Set 5 Game 32'})
PERIODS.update({(33,177): 'Set 5 Game 33'})
PERIODS.update({(33,178): 'Set 5 Game 34'})
PERIODS.update({(33,179): 'Set 5 Game 35'})
PERIODS.update({(33,180): 'Set 5 Game 36'})
PERIODS.update({(33,181): 'Set 5 Game 37'})
PERIODS.update({(33,182): 'Set 5 Game 38'})
PERIODS.update({(33,183): 'Set 5 Game 39'})
PERIODS.update({(33,184): 'Set 5 Game 40'})
PERIODS.update({(33,185): 'Set 5 Game 41'})
PERIODS.update({(33,186): 'Set 5 Game 42'})
PERIODS.update({(33,187): 'Set 5 Game 43'})
PERIODS.update({(33,188): 'Set 5 Game 44'})
PERIODS.update({(33,189): 'Set 5 Game 45'})
PERIODS.update({(33,190): 'Set 5 Game 46'})
PERIODS.update({(33,191): 'Set 5 Game 47'})
PERIODS.update({(33,192): 'Set 5 Game 48'})
PERIODS.update({(33,193): 'Set 5 Game 49'})
PERIODS.update({(33,194): 'Set 5 Game 50'})
PERIODS.update({(33,195): 'Set 5 Game 51'})
PERIODS.update({(33,196): 'Set 5 Game 52'})
PERIODS.update({(33,197): 'Set 5 Game 53'})
PERIODS.update({(33,198): 'Set 5 Game 54'})
PERIODS.update({(33,199): 'Set 5 Game 55'})
PERIODS.update({(33,200): 'Set 5 Game 56'})
PERIODS.update({(33,201): 'Set 5 Game 57'})
PERIODS.update({(33,202): 'Set 5 Game 58'})
PERIODS.update({(33,203): 'Set 5 Game 59'})
PERIODS.update({(33,204): 'Set 5 Game 60'})
PERIODS.update({(33,205): 'Set 5 Game 61'})
PERIODS.update({(33,206): 'Set 5 Game 62'})
PERIODS.update({(33,207): 'Set 5 Game 63'})
PERIODS.update({(33,208): 'Set 5 Game 64'})
PERIODS.update({(33,209): 'Set 5 Game 65'})
PERIODS.update({(33,210): 'Set 5 Game 66'})
PERIODS.update({(33,211): 'Set 5 Game 67'})
PERIODS.update({(33,212): 'Set 5 Game 68'})
PERIODS.update({(33,213): 'Set 5 Game 69'})
PERIODS.update({(33,214): 'Set 5 Game 70'})
PERIODS.update({(33,215): 'Set 5 Game 71'})
PERIODS.update({(33,216): 'Set 5 Game 72'})
PERIODS.update({(33,217): 'Set 5 Game 73'})
PERIODS.update({(33,218): 'Set 5 Game 74'})
PERIODS.update({(33,219): 'Set 5 Game 75'})
PERIODS.update({(33,220): 'Set 5 Game 76'})
PERIODS.update({(33,221): 'Set 5 Game 77'})
PERIODS.update({(33,222): 'Set 5 Game 78'})
PERIODS.update({(33,223): 'Set 5 Game 79'})
PERIODS.update({(33,224): 'Set 5 Game 80'})
PERIODS.update({(33,225): 'Set 5 Game 81'})
PERIODS.update({(33,226): 'Set 5 Game 82'})
PERIODS.update({(33,227): 'Set 5 Game 83'})
PERIODS.update({(33,228): 'Set 5 Game 84'})
PERIODS.update({(33,229): 'Set 5 Game 85'})
PERIODS.update({(33,230): 'Set 5 Game 86'})
PERIODS.update({(33,231): 'Set 5 Game 87'})
PERIODS.update({(33,232): 'Set 5 Game 88'})
PERIODS.update({(33,233): 'Set 5 Game 89'})
PERIODS.update({(33,234): 'Set 5 Game 90'})
PERIODS.update({(33,235): 'Set 5 Game 91'})
PERIODS.update({(33,236): 'Set 5 Game 92'})
PERIODS.update({(33,237): 'Set 5 Game 93'})
PERIODS.update({(33,238): 'Set 5 Game 94'})
PERIODS.update({(33,239): 'Set 5 Game 95'})
PERIODS.update({(33,240): 'Set 5 Game 96'})
PERIODS.update({(33,241): 'Set 5 Game 97'})
PERIODS.update({(33,242): 'Set 5 Game 98'})
PERIODS.update({(33,243): 'Set 5 Game 99'})
PERIODS.update({(33,244): 'Set 5 Game 100'})
PERIODS.update({(3,0): 'Game'})
PERIODS.update({(3,1): '1st Half'})
PERIODS.update({(3,2): '2nd Half'})
PERIODS.update({(3,3): '1st Inning'})
PERIODS.update({(3,4): '2nd Inning'})
PERIODS.update({(3,5): '3rd Inning'})
PERIODS.update({(3,6): '4th Inning'})
PERIODS.update({(3,7): '5th Inning'})
PERIODS.update({(3,8): '6th Inning'})
PERIODS.update({(3,9): '7th Inning'})
PERIODS.update({(3,10): '8th Inning'})
PERIODS.update({(3,11): '9th Inning'})
PERIODS.update({(3,12): 'Innings 1 to 7'})
PERIODS.update({(15,0): 'Game'})
PERIODS.update({(15,1): '1st Half'})
PERIODS.update({(15,2): '2nd Half'})
PERIODS.update({(15,3): '1st Quarter'})
PERIODS.update({(15,4): '2nd Quarter'})
PERIODS.update({(15,5): '3rd Quarter'})
PERIODS.update({(15,6): '4th Quarter'})
PERIODS.update({(19,0): 'OT Included'})
PERIODS.update({(19,1): '1st Period'})
PERIODS.update({(19,2): '2nd Period'})
PERIODS.update({(19,3): '3rd Period'})
PERIODS.update({(19,4): 'Overtime'})
PERIODS.update({(19,5): 'Shootout'})
PERIODS.update({(19,6): 'Regulation Time'})
PERIODS.update({(26,0): 'Match'})
PERIODS.update({(26,1): '1st Half'})
PERIODS.update({(26,2): '2nd Half'})
PERIODS.update({(27,0): 'Match'})
PERIODS.update({(27,1): '1st Half'})
PERIODS.update({(27,2): '2nd Half'})
PERIODS.update({(10,0): 'Match'})
PERIODS.update({(10,1): '1st Set'})
PERIODS.update({(10,2): '2nd Set'})
PERIODS.update({(10,3): '3rd Set'})
PERIODS.update({(10,4): '4th Set'})
PERIODS.update({(10,5): '5th Set'})
PERIODS.update({(8,0): 'Match'})
PERIODS.update({(8,1): 'Inning 1'})
PERIODS.update({(8,2): 'Inning 2'})
PERIODS.update({(8,3): 'Inning 1 Overs 1-6'})
PERIODS.update({(8,4): 'Inning 1 Overs 7-10'})
PERIODS.update({(8,5): 'Inning 1 Overs 11-15'})
PERIODS.update({(8,6): 'Inning 1 Overs 16-20'})
PERIODS.update({(8,7): 'Inning 1 Overs 1-5'})
PERIODS.update({(8,8): 'Inning 1 Overs 6-10'})
PERIODS.update({(8,9): 'Inning 1 Overs 21-25'})
PERIODS.update({(8,10): 'Inning 1 Overs 26-30'})
PERIODS.update({(8,11): 'Inning 1 Overs 31-35'})
PERIODS.update({(8,12): 'Inning 1 Overs 36-40'})
PERIODS.update({(8,13): 'Inning 1 Overs 41-45'})
PERIODS.update({(8,14): 'Inning 1 Overs 46-50'})
PERIODS.update({(8,15): 'Inning 1 Pair 1'})
PERIODS.update({(8,16): 'Inning 1 Over 1'})
PERIODS.update({(8,17): 'Inning 1 Over 2'})
PERIODS.update({(8,18): 'Inning 1 Over 3'})
PERIODS.update({(8,19): 'Inning 1 Over 4'})
PERIODS.update({(8,20): 'Inning 1 Over 5'})
PERIODS.update({(8,21): 'Inning 1 Over 6'})
PERIODS.update({(8,22): 'Inning 1 Over 7'})
PERIODS.update({(8,23): 'Inning 1 Over 8'})
PERIODS.update({(8,24): 'Inning 1 Over 9'})
PERIODS.update({(8,25): 'Inning 1 Over 10'})
PERIODS.update({(8,26): 'Inning 1 Over 11'})
PERIODS.update({(8,27): 'Inning 1 Over 12'})
PERIODS.update({(8,28): 'Inning 1 Over 13'})
PERIODS.update({(8,29): 'Inning 1 Over 14'})
PERIODS.update({(8,30): 'Inning 1 Over 15'})
PERIODS.update({(8,31): 'Inning 1 Over 16'})
PERIODS.update({(8,32): 'Inning 1 Over 17'})
PERIODS.update({(8,33): 'Inning 1 Over 18'})
PERIODS.update({(8,34): 'Inning 1 Over 19'})
PERIODS.update({(8,35): 'Inning 1 Over 20'})
PERIODS.update({(8,36): 'Inning 1 Over 21'})
PERIODS.update({(8,37): 'Inning 1 Over 22'})
PERIODS.update({(8,38): 'Inning 1 Over 23'})
PERIODS.update({(8,39): 'Inning 1 Over 24'})
PERIODS.update({(8,40): 'Inning 1 Over 25'})
PERIODS.update({(8,41): 'Inning 1 Over 26'})
PERIODS.update({(8,42): 'Inning 1 Over 27'})
PERIODS.update({(8,43): 'Inning 1 Over 28'})
PERIODS.update({(8,44): 'Inning 1 Over 29'})
PERIODS.update({(8,45): 'Inning 1 Over 30'})
PERIODS.update({(8,46): 'Inning 1 Over 31'})
PERIODS.update({(8,47): 'Inning 1 Over 32'})
PERIODS.update({(8,48): 'Inning 1 Over 33'})
PERIODS.update({(8,49): 'Inning 1 Over 34'})
PERIODS.update({(8,50): 'Inning 1 Over 35'})
PERIODS.update({(8,51): 'Inning 1 Over 36'})
PERIODS.update({(8,52): 'Inning 1 Over 37'})
PERIODS.update({(8,53): 'Inning 1 Over 38'})
PERIODS.update({(8,54): 'Inning 1 Over 39'})
PERIODS.update({(8,55): 'Inning 1 Over 40'})
PERIODS.update({(8,56): 'Inning 1 Over 41'})
PERIODS.update({(8,57): 'Inning 1 Over 42'})
PERIODS.update({(8,58): 'Inning 1 Over 43'})
PERIODS.update({(8,59): 'Inning 1 Over 44'})
PERIODS.update({(8,60): 'Inning 1 Over 45'})
PERIODS.update({(8,61): 'Inning 1 Over 46'})
PERIODS.update({(8,62): 'Inning 1 Over 47'})
PERIODS.update({(8,63): 'Inning 1 Over 48'})
PERIODS.update({(8,64): 'Inning 1 Over 49'})
PERIODS.update({(8,65): 'Inning 1 Over 50'})
PERIODS.update({(8,66): 'Super Over 1'})
PERIODS.update({(8,67): 'Inning 2 Overs 1-6'})
PERIODS.update({(8,68): 'Inning 2 Overs 7-10'})
PERIODS.update({(8,69): 'Inning 2 Overs 11-15'})
PERIODS.update({(8,70): 'Inning 2 Overs 16-20'})
PERIODS.update({(8,71): 'Inning 2 Overs 1-5'})
PERIODS.update({(8,72): 'Inning 2 Overs 6-10'})
PERIODS.update({(8,73): 'Inning 2 Overs 21-25'})
PERIODS.update({(8,74): 'Inning 2 Overs 26-30'})
PERIODS.update({(8,75): 'Inning 2 Overs 31-35'})
PERIODS.update({(8,76): 'Inning 2 Overs 36-40'})
PERIODS.update({(8,77): 'Inning 2 Overs 41-45'})
PERIODS.update({(8,78): 'Inning 2 Overs 46-50'})
PERIODS.update({(8,79): 'Inning 2 Pair 1'})
PERIODS.update({(8,80): 'Inning 2 Over 1'})
PERIODS.update({(8,81): 'Inning 2 Over 2'})
PERIODS.update({(8,82): 'Inning 2 Over 3'})
PERIODS.update({(8,83): 'Inning 2 Over 4'})
PERIODS.update({(8,84): 'Inning 2 Over 5'})
PERIODS.update({(8,85): 'Inning 2 Over 6'})
PERIODS.update({(8,86): 'Inning 2 Over 7'})
PERIODS.update({(8,87): 'Inning 2 Over 8'})
PERIODS.update({(8,88): 'Inning 2 Over 9'})
PERIODS.update({(8,89): 'Inning 2 Over 10'})
PERIODS.update({(8,90): 'Inning 2 Over 11'})
PERIODS.update({(8,91): 'Inning 2 Over 12'})
PERIODS.update({(8,92): 'Inning 2 Over 13'})
PERIODS.update({(8,93): 'Inning 2 Over 14'})
PERIODS.update({(8,94): 'Inning 2 Over 15'})
PERIODS.update({(8,95): 'Inning 2 Over 16'})
PERIODS.update({(8,96): 'Inning 2 Over 17'})
PERIODS.update({(8,97): 'Inning 2 Over 18'})
PERIODS.update({(8,98): 'Inning 2 Over 19'})
PERIODS.update({(8,99): 'Inning 2 Over 20'})
PERIODS.update({(8,100): 'Inning 2 Over 21'})
PERIODS.update({(8,101): 'Inning 2 Over 22'})
PERIODS.update({(8,102): 'Inning 2 Over 23'})
PERIODS.update({(8,103): 'Inning 2 Over 24'})
PERIODS.update({(8,104): 'Inning 2 Over 25'})
PERIODS.update({(8,105): 'Inning 2 Over 26'})
PERIODS.update({(8,106): 'Inning 2 Over 27'})
PERIODS.update({(8,107): 'Inning 2 Over 28'})
PERIODS.update({(8,108): 'Inning 2 Over 29'})
PERIODS.update({(8,109): 'Inning 2 Over 30'})
PERIODS.update({(8,110): 'Inning 2 Over 31'})
PERIODS.update({(8,111): 'Inning 2 Over 32'})
PERIODS.update({(8,112): 'Inning 2 Over 33'})
PERIODS.update({(8,113): 'Inning 2 Over 34'})
PERIODS.update({(8,114): 'Inning 2 Over 35'})
PERIODS.update({(8,115): 'Inning 2 Over 36'})
PERIODS.update({(8,116): 'Inning 2 Over 37'})
PERIODS.update({(8,117): 'Inning 2 Over 38'})
PERIODS.update({(8,118): 'Inning 2 Over 39'})
PERIODS.update({(8,119): 'Inning 2 Over 40'})
PERIODS.update({(8,120): 'Inning 2 Over 41'})
PERIODS.update({(8,121): 'Inning 2 Over 42'})
PERIODS.update({(8,122): 'Inning 2 Over 43'})
PERIODS.update({(8,123): 'Inning 2 Over 44'})
PERIODS.update({(8,124): 'Inning 2 Over 45'})
PERIODS.update({(8,125): 'Inning 2 Over 46'})
PERIODS.update({(8,126): 'Inning 2 Over 47'})
PERIODS.update({(8,127): 'Inning 2 Over 48'})
PERIODS.update({(8,128): 'Inning 2 Over 49'})
PERIODS.update({(8,129): 'Inning 2 Over 50'})
PERIODS.update({(8,130): 'Super Over 2'})
PERIODS.update({(8,131): 'Inning 1&2 Over 1-6'})
PERIODS.update({(8,132): 'Inning 1&2 Over 1-10'})
PERIODS.update({(8,133): 'Inning 1&2 Over 1-15'})
PERIODS.update({(8,134): 'Inning 1&2 Over 1-20'})
PERIODS.update({(8,135): 'Inning 1&2 Over 1'})
PERIODS.update({(8,136): 'Inning 1&2 Over 2'})
PERIODS.update({(8,137): 'Inning 1&2 Over 3'})
PERIODS.update({(8,138): 'Inning 1&2 Over 4'})
PERIODS.update({(8,139): 'Inning 1&2 Over 5'})
PERIODS.update({(8,140): 'Inning 1&2 Over 6'})
PERIODS.update({(8,141): 'Inning 1&2 Over 7'})
PERIODS.update({(8,142): 'Inning 1&2 Over 8'})
PERIODS.update({(8,143): 'Inning 1&2 Over 9'})
PERIODS.update({(8,144): 'Inning 1&2 Over 10'})
PERIODS.update({(8,145): 'Inning 1&2 Over 11'})
PERIODS.update({(8,146): 'Inning 1&2 Over 12'})
PERIODS.update({(8,147): 'Inning 1&2 Over 13'})
PERIODS.update({(8,148): 'Inning 1&2 Over 14'})
PERIODS.update({(8,149): 'Inning 1&2 Over 15'})
PERIODS.update({(8,150): 'Inning 1&2 Over 16'})
PERIODS.update({(8,151): 'Inning 1&2 Over 17'})
PERIODS.update({(8,152): 'Inning 1&2 Over 18'})
PERIODS.update({(8,153): 'Inning 1&2 Over 19'})
PERIODS.update({(8,154): 'Inning 1&2 Over 20'})
PERIODS.update({(8,155): 'Inning 1 Overs 1-10'})
PERIODS.update({(8,156): 'Inning 1 Overs 1-15'})
PERIODS.update({(8,157): 'Inning 1 Overs 1-20'})
PERIODS.update({(8,158): 'Inning 2 Overs 1-10'})
PERIODS.update({(8,159): 'Inning 2 Overs 1-15'})
PERIODS.update({(8,160): 'Inning 2 Overs 1-20'})
PERIODS.update({(17,0): 'Matchups'})
PERIODS.update({(18,0): 'Match'})
PERIODS.update({(18,1): '1st Half'})
PERIODS.update({(18,2): '2nd Half'})
PERIODS.update({(28,0): 'Match'})
PERIODS.update({(28,1): '1st Frame'})
PERIODS.update({(34,0): 'Match'})
PERIODS.update({(34,1): '1st Set'})
PERIODS.update({(34,2): '2nd Set'})
PERIODS.update({(34,3): '3rd Set'})
PERIODS.update({(34,4): '4th Set'})
PERIODS.update({(34,5): '5th Set'})
PERIODS.update({(39,0): 'Game'})
PERIODS.update({(39,1): '1st Half'})
PERIODS.update({(39,2): '2nd Half'})
PERIODS.update({(39,3): '1st Quarter'})
PERIODS.update({(39,4): '2nd Quarter'})
PERIODS.update({(39,5): '3rd Quarter'})
PERIODS.update({(39,6): '4th Quarter'})
PERIODS.update({(40,0): 'Matchups'})
PERIODS.update({(56,0): 'Matchups'})
PERIODS.update({(1,0): 'Match'})
PERIODS.update({(1,1): '1st Game'})
PERIODS.update({(1,2): '2nd Game'})
PERIODS.update({(1,3): '3rd Game'})
PERIODS.update({(2,0): 'Match'})
PERIODS.update({(2,1): '1st Half'})
PERIODS.update({(2,2): '2nd Half'})
PERIODS.update({(5,0): 'Match'})
PERIODS.update({(5,1): '1st Set'})
PERIODS.update({(5,2): '2nd Set'})
PERIODS.update({(5,3): '3rd Set'})
PERIODS.update({(41,0): 'Matchups'})
PERIODS.update({(6,0): 'Fight'})
PERIODS.update({(7,0): 'Match'})
PERIODS.update({(43,0): 'Matchups'})
PERIODS.update({(57,0): 'Matchups'})
PERIODS.update({(9,0): 'Game'})
PERIODS.update({(9,1): '1st End'})
PERIODS.update({(45,0): 'Matchups'})
PERIODS.update({(58,0): 'Matchups'})
PERIODS.update({(13,0): 'Match'})
PERIODS.update({(13,1): '1st Half'})
PERIODS.update({(13,2): '2nd Half'})
PERIODS.update({(44,0): 'Matchups'})
PERIODS.update({(16,0): 'Match'})
PERIODS.update({(16,1): '1st Half'})
PERIODS.update({(16,2): '2nd Half'})
PERIODS.update({(22,0): 'Fight'})
PERIODS.update({(22,1): 'Round 1'})
PERIODS.update({(22,2): 'Round 2'})
PERIODS.update({(22,3): 'Round 3'})
PERIODS.update({(22,4): 'Round 4'})
PERIODS.update({(22,5): 'Round 5'})
PERIODS.update({(63,0): 'Matchups'})
PERIODS.update({(55,0): 'Match'})
PERIODS.update({(37,0): 'Match'})
PERIODS.update({(37,1): '1st Set Winner'})
PERIODS.update({(37,2): '2nd Set Winner'})
PERIODS.update({(37,3): '3rd Set Winner'})
PERIODS.update({(42,0): 'Matchups'})
PERIODS.update({(30,0): 'Game'})
PERIODS.update({(30,1): '1st Half'})
PERIODS.update({(30,2): '2st Half'})
PERIODS.update({(31,0): 'Match'})
PERIODS.update({(31,1): '1st Game'})
PERIODS.update({(31,2): '2nd Game'})
PERIODS.update({(31,3): '3rd Game'})
PERIODS.update({(31,4): '4th Game'})
PERIODS.update({(31,5): '5th Game'})
PERIODS.update({(65,0): 'Match'})
PERIODS.update({(32,0): 'Match'})
PERIODS.update({(32,1): '1st Game'})
PERIODS.update({(32,2): '2nd Game'})
PERIODS.update({(32,3): '3rd Game'})
PERIODS.update({(32,4): '4th Game'})
PERIODS.update({(32,5): '5th Game'})
PERIODS.update({(32,6): '6th Game'})
PERIODS.update({(36,0): 'Match'})
PERIODS.update({(36,1): '1st Period'})
PERIODS.update({(36,2): '2nd Period'})
PERIODS.update({(36,3): '3rd Period'})
PERIODS.update({(36,4): '4th Period'})

BOOKS = set()
BOOKS.add('Stake')
BOOKS.add('Betano')
BOOKS.add('bet365')
BOOKS.add('Hollywoodbets')
BOOKS.add('Bet9ja')
BOOKS.add('Betika')
BOOKS.add('SportyBet')
BOOKS.add('Betnacional')
BOOKS.add('Betfair')
BOOKS.add('Sportingbet')
BOOKS.add('EstrelaBet')
BOOKS.add('MELbet')
BOOKS.add('Winline')
BOOKS.add('Betway')
BOOKS.add('Wplay.co')
BOOKS.add('Brazino777')
BOOKS.add('Caliente')
BOOKS.add('BetKing')
BOOKS.add('Superbet')
BOOKS.add('Fortuna')
BOOKS.add('Nesine')
BOOKS.add('YesPlay')
BOOKS.add('BetPlay')
BOOKS.add('Unibet')
BOOKS.add('Adjarabet')
BOOKS.add('Rushbet')
BOOKS.add('Stoiximan')
BOOKS.add('FDJ')
BOOKS.add('Novibet')
BOOKS.add('Sisal')
BOOKS.add('Sky Bet')
BOOKS.add('Paddy Power')
BOOKS.add('1xBet')
BOOKS.add('Tipsport')
BOOKS.add('Ladbrokes')
BOOKS.add('pixbet')
BOOKS.add('William Hill')
BOOKS.add('Parimatch')
BOOKS.add('Veikkaus Pitkäveto')
BOOKS.add('HKJC')
BOOKS.add('FanDuel')
BOOKS.add('Betsson')
BOOKS.add('DraftKings')
BOOKS.add('Mozzart')
BOOKS.add('Winbet')
BOOKS.add('bwin')
BOOKS.add('Norsk Tipping')
BOOKS.add('Tipico')
BOOKS.add('TOTO')
BOOKS.add('BetClic')
BOOKS.add('Coral')
BOOKS.add('Blaze')
BOOKS.add('Bet.era')
BOOKS.add('KTO')
BOOKS.add('Sportium')
BOOKS.add('Svenskaspel Oddset')
BOOKS.add('Favbet')
BOOKS.add('Caesars Sportsbook')
BOOKS.add('Codere')
BOOKS.add('ATG')
BOOKS.add('Liga Stavok')
BOOKS.add('Odibets')
BOOKS.add('500.com')
BOOKS.add('Betcris')
BOOKS.add('betPawa')
BOOKS.add('Sazkabet')
BOOKS.add('BetWinner')
BOOKS.add('Lottomatica')
BOOKS.add('Inkabet')
BOOKS.add('PMU')
BOOKS.add('Nubet')
BOOKS.add('PalmsBet')
BOOKS.add('Galera.bet')
BOOKS.add('Te Apuesto')
BOOKS.add('BetCity')
BOOKS.add('Roobet')
BOOKS.add('Swisslos')
BOOKS.add('win2day')
BOOKS.add('MrJack.bet')
BOOKS.add('Fortebet')
BOOKS.add('GoldBet')
BOOKS.add('F12.bet')
BOOKS.add('Snai')
BOOKS.add('Meridianbet')
BOOKS.add('BetFlag')
BOOKS.add('iddaa')
BOOKS.add('Rivalo')
BOOKS.add('TAB.com.au')
BOOKS.add('LeoVegas')
BOOKS.add('Winamax')
BOOKS.add('STSbet')
BOOKS.add('Yajuego')
BOOKS.add('Easybet')
BOOKS.add('BetCity.nl')
BOOKS.add('Pamestoixima')
BOOKS.add('Danske Spil Oddset')
BOOKS.add('ZEturf')
BOOKS.add('Lottoland')
BOOKS.add('SuperSport')
BOOKS.add('Synot Tip')
BOOKS.add('OlyBet')
BOOKS.add('BC.Game')
BOOKS.add('TippmixPro')
BOOKS.add('Chance')
BOOKS.add('Singapore Pools')
BOOKS.add('Betlive')
BOOKS.add('22BET')
BOOKS.add('Marathonbet')
BOOKS.add('Eurobet')
BOOKS.add('Coolbet')
BOOKS.add('Gamdom')
BOOKS.add('World Sports Betting')
BOOKS.add('Betsafe')
BOOKS.add('Boylesports')
BOOKS.add('planetwin365')
BOOKS.add('Nike')
BOOKS.add('Admiral')
BOOKS.add('TwinSpires')
BOOKS.add('efbet')
BOOKS.add('BetMGM')
BOOKS.add('Optibet')
BOOKS.add('Interwetten')
BOOKS.add('TVG')
BOOKS.add('bet-at-home')
BOOKS.add('Betfred')
BOOKS.add('Olimp')
BOOKS.add('888 Sport')
BOOKS.add('Grosvenor Casinos')
BOOKS.add('NetBet')
BOOKS.add('TAB.co.nz')
BOOKS.add('Oley')
BOOKS.add('TOPsport')
BOOKS.add('BetVictor')
BOOKS.add('20Bet')
BOOKS.add('Bilyoner')
BOOKS.add('10bet')
BOOKS.add('Inbet')
BOOKS.add('Crystalbet')
BOOKS.add('Virgin Bet')
BOOKS.add('Misli')
BOOKS.add('Casa Pariurilor')
BOOKS.add('32Red')
BOOKS.add('Paf')
BOOKS.add('PlayaBets')
BOOKS.add('Pagbet')
BOOKS.add('MaxBet.rs')
BOOKS.add('Pinnacle')
BOOKS.add('winmasters')
BOOKS.add('TotoGaming')
BOOKS.add('MegApuesta')
BOOKS.add('SunBet')
BOOKS.add('Polla Chilena')
BOOKS.add('Aposta.La')
BOOKS.add('8888')
BOOKS.add('Betshop')
BOOKS.add('NineCasino')
BOOKS.add('Winner.co.il')
BOOKS.add('europebet')
BOOKS.add('Supabets')
BOOKS.add('Rikstoto')
BOOKS.add('TonyBet')
BOOKS.add('Leon Bets')
BOOKS.add('Bangbet')
BOOKS.add('Sports Interaction')
BOOKS.add('iBet789')
BOOKS.add('Bet Plays')
BOOKS.add('ESC Online')
BOOKS.add('Gets Bet')
BOOKS.add('Leader-Bet')
BOOKS.add('Dafabet')
BOOKS.add('ComeOn!')
BOOKS.add('Trust Dice')
BOOKS.add('Bluechip')
BOOKS.add('VBET')
BOOKS.add('Mystake')
BOOKS.add('Rivalry')
BOOKS.add('Duelbits')
BOOKS.add('Gal Sport Betting')
BOOKS.add('PremierBet')
BOOKS.add('Velobet')
BOOKS.add('GGBet')
BOOKS.add('Soccabet')
BOOKS.add('Giocodigitale')
BOOKS.add('Casa de Apostas')
BOOKS.add('Smarkets')
BOOKS.add('eTipos')
BOOKS.add('Circus')
BOOKS.add('RojaBet')
BOOKS.add('Solverde.pt')
BOOKS.add('Sportsbet.io')
BOOKS.add('Satsport')
BOOKS.add('Premier Kladionica')
BOOKS.add('WasafiBet')
BOOKS.add('MerkurXtip')
BOOKS.add('Strendus')
BOOKS.add('Luckia')
BOOKS.add('Casumo')
BOOKS.add('Genybet')
BOOKS.add('Napoleon Games')
BOOKS.add('7bet')
BOOKS.add('Alphawin')
BOOKS.add('HPIbet')
BOOKS.add('Loterie Romande')
BOOKS.add('Rollbit')
BOOKS.add('Coins.game')
BOOKS.add('Betpix')
BOOKS.add('Crocobet')
BOOKS.add('WWin')
BOOKS.add('SportPesa')
BOOKS.add('Bet UK')
BOOKS.add('Mr Green')
BOOKS.add('BetPoint')
BOOKS.add('Matchbook')
BOOKS.add('Betboo')
BOOKS.add('Cosmobet')
BOOKS.add('BataviaBets')
BOOKS.add('NordicBet')
BOOKS.add('Bet3000')
BOOKS.add('BalkanBet')
BOOKS.add('Qbet')
BOOKS.add('LV BET')
BOOKS.add('Esportiva.bet')
BOOKS.add('Tuttur')
BOOKS.add('Baji')
BOOKS.add('Premier')
BOOKS.add('Casino Portugal')
BOOKS.add('Sesame')
BOOKS.add('Expekt')
BOOKS.add('Meridianbet.co.tz')
BOOKS.add('SpinBet')
BOOKS.add('tipp3')
BOOKS.add('Maxline')
BOOKS.add('Gbets')
BOOKS.add('Neds')
BOOKS.add('AccessBET')
BOOKS.add('forBET')
BOOKS.add('SBOBET')
BOOKS.add('PowerPlay')
BOOKS.add('Betsul')
BOOKS.add('Cashpoint')
BOOKS.add('Volcano')
BOOKS.add('e-stave')
BOOKS.add('thepools')
BOOKS.add('Marsbet')
BOOKS.add('BetFury')
BOOKS.add('NairaBet')
BOOKS.add('Bet.co.za')
BOOKS.add('eTopaz')
BOOKS.add('RaceBets')
BOOKS.add('Thunderpick')
BOOKS.add('Cwinz')
BOOKS.add('MaxBet.ro')
BOOKS.add('Betcenter')
BOOKS.add('888Bet Tanzania')
BOOKS.add('Afropari')
BOOKS.add('Bingoal')
BOOKS.add('Placard')
BOOKS.add('Bet On Alfa')
BOOKS.add('Rajabets')
BOOKS.add('Betdaq')
BOOKS.add('BETFAN')
BOOKS.add('ibet')
BOOKS.add('Betsat')
BOOKS.add('Tote')
BOOKS.add('Boomerang-Bet')
BOOKS.add('MyWinners')
BOOKS.add('Mr Bet')
BOOKS.add('Mr Bit')
BOOKS.add('Winner.ro')
BOOKS.add('ZEbet')
BOOKS.add('BetOnRed')
BOOKS.add('Prva Sportska Kladionica')
BOOKS.add('Goldenbet')
BOOKS.add('BetRivers.NET')
BOOKS.add('kwiff')
BOOKS.add('Bet25')
BOOKS.add('bilbet')
BOOKS.add('Marca Apuestas')
BOOKS.add('partypoker')
BOOKS.add('WettArena')
BOOKS.add('12BET')
BOOKS.add('DOXXbet')
BOOKS.add('Interbet.co.za')
BOOKS.add('SportLife')
BOOKS.add('CopyBet')
BOOKS.add('Supermatch')
BOOKS.add('Cloudbet')
BOOKS.add('Megapari')
BOOKS.add('Rizk')
BOOKS.add('Zenit')
BOOKS.add('Snabbare')
BOOKS.add('JuegaEnLinea')
BOOKS.add('Spreadex')
BOOKS.add('Fafabet')
BOOKS.add('Rolletto')
BOOKS.add('QuiGioco')
BOOKS.add('Lucky Block')
BOOKS.add('310win')
BOOKS.add('Casino GranMadrid Online')
BOOKS.add('Midnite')
BOOKS.add('N1bet')
BOOKS.add('Bdmbet')
BOOKS.add('188BET')
BOOKS.add('Betspino')
BOOKS.add('Borgata Online')
BOOKS.add('Loteria Națională')
BOOKS.add('1xStavka')
BOOKS.add('BetInAsia')
BOOKS.add('RETABet')
BOOKS.add('Scooore')
BOOKS.add('Betaland')
BOOKS.add('Off Track Betting')
BOOKS.add('Pferdewetten')
BOOKS.add('ETOTO')
BOOKS.add('Cbet')
BOOKS.add('TOTALbet')
BOOKS.add('tipwin')
BOOKS.add('Svenplay')
BOOKS.add('Tab Gold')
BOOKS.add('Mansion88')
BOOKS.add('500.casino')
BOOKS.add('Zamba')
BOOKS.add('Versus')
BOOKS.add('Epicbet')
BOOKS.add('Winz.io')
BOOKS.add('BetXchange')
BOOKS.add('Bitsler')
BOOKS.add('MSL')
BOOKS.add('AK BETS')
BOOKS.add('PlayUp')
BOOKS.add('Hajper')
BOOKS.add('Merrybet')
BOOKS.add('TABtouch')
BOOKS.add('Germania')
BOOKS.add('Betmotion')
BOOKS.add('Kirolbet')
BOOKS.add('Chips.gg')
BOOKS.add('PublicWin')
BOOKS.add('Vave')
BOOKS.add('Wild.io')
BOOKS.add('Bons')
BOOKS.add('Betiton')
BOOKS.add('Eurotierce')
BOOKS.add('Picklebet')
BOOKS.add('Plexbet')
BOOKS.add('bet7')
BOOKS.add('highbet')
BOOKS.add('Wintoto')
BOOKS.add('QuinnBet')
BOOKS.add('DavBet')
BOOKS.add('Tennisi')
BOOKS.add('Tiptorro')
BOOKS.add('LEX')
BOOKS.add('Parimatch.co.uk')
BOOKS.add('1RED')
BOOKS.add('KwikBet')
BOOKS.add('CryptoLeo')
BOOKS.add('TopSport.com.au')
BOOKS.add('Fairspin')
BOOKS.add('Mr.Mega')
BOOKS.add('Pinnbet')
BOOKS.add('Bethard')
BOOKS.add('1Bet')
BOOKS.add('Space Casino')
BOOKS.add('DomusBet')
BOOKS.add('StarSports')
BOOKS.add('Linebet')
BOOKS.add('VinciTu')
BOOKS.add('LiveBet')
BOOKS.add('ivibet')
BOOKS.add('Betitaly')
BOOKS.add('Jokabet')
BOOKS.add('HPYBET')
BOOKS.add('FortuneJack')
BOOKS.add('GemBet')
BOOKS.add('PIWI247')
BOOKS.add('All British Casino')
BOOKS.add('Betters')
BOOKS.add('Paston')
BOOKS.add('MONRO')
BOOKS.add('Sol Casino')
BOOKS.add('4rabet')
BOOKS.add('CampoBet')
BOOKS.add('Punterz')
BOOKS.add('Betti')
BOOKS.add('BlueBet')
BOOKS.add('BetOlimp')
BOOKS.add('Woocasino')
BOOKS.add('DiceBet')
BOOKS.add('JET')
BOOKS.add('CasinoMania')
BOOKS.add('Bet Live')
BOOKS.add('STAR BET')
BOOKS.add('PlayBonds')
BOOKS.add('Wettstar Pferdewetten')
BOOKS.add('betwin360')
BOOKS.add('SpeedyBet')
BOOKS.add('Fonbet')
BOOKS.add('Juegging')
BOOKS.add('Badshahcric')
BOOKS.add('M-Bet')
BOOKS.add('FanTeam')
BOOKS.add('HeySpin')
BOOKS.add('Lala.bet')
BOOKS.add('2win')
BOOKS.add('replatz.it')
BOOKS.add('Spinanga')
BOOKS.add('Malina')
BOOKS.add('Rabona')
BOOKS.add('YoSports')
BOOKS.add('Spelet')
BOOKS.add('Satbet')
BOOKS.add('Chipstars.bet')
BOOKS.add('WickedBet')
BOOKS.add('InterBets')
BOOKS.add('GO+bet')
BOOKS.add('888Bet Mozambique')
BOOKS.add('Hollywood Races')
BOOKS.add('Jojobet')
BOOKS.add('Planet Sport Bet')
BOOKS.add('BetGoodwin')
BOOKS.add('Freshbet')
BOOKS.add('Winnerz')
BOOKS.add('Razed')
BOOKS.add('Karamba')
BOOKS.add('Campeonbet')
BOOKS.add('LEGZO')
BOOKS.add('Sporting Index')
BOOKS.add('sportbet')
BOOKS.add('Bet777')
BOOKS.add('Izzi Casino')
BOOKS.add('Prontobet')
BOOKS.add('Riobet')
BOOKS.add('Play Fast Casino')
BOOKS.add('Palmerbet')
BOOKS.add('Sirwin')
BOOKS.add('WinSpirit')
BOOKS.add('1xBit')
BOOKS.add('JOKERBET.es')
BOOKS.add('SlotV')
BOOKS.add('Football Pools')
BOOKS.add('SapphireBet')
BOOKS.add('SBbet')
BOOKS.add('Vivatbet')
BOOKS.add('Guts')
BOOKS.add('BET99')
BOOKS.add('JackpotcityCasino')
BOOKS.add('Overplus')
BOOKS.add('BK8')
BOOKS.add('betPARX')
BOOKS.add('Horuscasino')
BOOKS.add('PZBuk')
BOOKS.add('SoccerShop')
BOOKS.add('MobileBet')
BOOKS.add('PinterBet')
BOOKS.add('Drip Casino')
BOOKS.add('Excitewin')
BOOKS.add('Jackbit')
BOOKS.add('BetConnect')
BOOKS.add('BetMais')
BOOKS.add('Champion Bet')
BOOKS.add('LiliBet')
BOOKS.add('Newgioco')
BOOKS.add('STARDA')
BOOKS.add('1win')
BOOKS.add('Citobet')
BOOKS.add('Frank Sports')
BOOKS.add('Betting.co.zm')
BOOKS.add('FiveBet')
BOOKS.add('helabet')
BOOKS.add('Sportmarket')
BOOKS.add('Tedbet')
BOOKS.add('TVBet')
BOOKS.add('VinciTuBet')
BOOKS.add('Betbird')
BOOKS.add('Boomerang')
BOOKS.add('Betole')
BOOKS.add('Giochi Telematici')
BOOKS.add('Cyprus Sporting Clubs')
BOOKS.add('BetAmerica')
BOOKS.add('Betplay.io')
BOOKS.add('PUB Casino')
BOOKS.add('Ubet.kz')
BOOKS.add('Fresh Casino')
BOOKS.add('Casinia')
BOOKS.add('Betfinal')
BOOKS.add('Stevenhills')
BOOKS.add('Golden Palace Sports')
BOOKS.add('PariPesa')
BOOKS.add('Rocketpot')
BOOKS.add('Nossa Aposta')
BOOKS.add('Mega Dice')
BOOKS.add('BallyBet')
BOOKS.add('Marshalls World of Sport')
BOOKS.add('HoliganBet')
BOOKS.add('Macau Slot')
BOOKS.add('Betzino')
BOOKS.add('Snatch Casino')
BOOKS.add('Kripty')
BOOKS.add('BetDeluxe')
BOOKS.add('Casino-X Sports')
BOOKS.add('Weiss')
BOOKS.add('Club Riches')
BOOKS.add('Rebellion Casino')
BOOKS.add('RTBet')
BOOKS.add('Scommettendo')
BOOKS.add('enjoybet')
BOOKS.add('McBookie')
BOOKS.add('SportingBull')
BOOKS.add('FEZbet')
BOOKS.add('A McLean Bookmakers')
BOOKS.add('BetGRW')
BOOKS.add('Crypto Games')
BOOKS.add('BetBeast')
BOOKS.add('Gana777')
BOOKS.add('Fastbet')
BOOKS.add('casibom')
BOOKS.add('Spassino')
BOOKS.add('The Online Casino')
BOOKS.add('Loot.bet')
BOOKS.add('Vicbet')
BOOKS.add('Justbit')
BOOKS.add('Tuskcasino')
BOOKS.add('Betobet')
BOOKS.add('World Star Betting')
BOOKS.add('Magic Betting')
BOOKS.add('888starz.bet')
BOOKS.add('bob')
BOOKS.add('WSM Casino')
BOOKS.add('Betandyou')
BOOKS.add('Pribet')
BOOKS.add('SATSport247')
BOOKS.add('Megabet Plus')
BOOKS.add('NovaJackpot')
BOOKS.add('Asianconnect')
BOOKS.add('Conquestador')
BOOKS.add('BetWarrior')
BOOKS.add('Betdex')
BOOKS.add('Starcasinosport')
BOOKS.add('mr.play')
BOOKS.add('BetRebels')
BOOKS.add('Totolotek')
BOOKS.add('Chezacash')
BOOKS.add('Terrybet')
BOOKS.add('Blitz')
BOOKS.add('BetMatch')
BOOKS.add('Bets.io')
BOOKS.add('Dexsport')
BOOKS.add('Heybets')
BOOKS.add('0xBET')
BOOKS.add('Betsmove')
BOOKS.add('i7Bet')
BOOKS.add('France Pari')
BOOKS.add('Betibet')
BOOKS.add('DexterBet')
BOOKS.add('Hespsibahis')
BOOKS.add('Instabet')
BOOKS.add('Sportuna')
BOOKS.add('Zodiacbet')
BOOKS.add('Izibet')
BOOKS.add('PlanetOfBets')
BOOKS.add('eBetX')
BOOKS.add('Luckybull')
BOOKS.add('Betswap.gg')
BOOKS.add('ExclusiveBet')
BOOKS.add('Orbit Exchange')
BOOKS.add('WynnBET')
BOOKS.add('Slotimo')
BOOKS.add('Sportaza')
BOOKS.add('Boomerang-Casino')
BOOKS.add('Bet-Football')
BOOKS.add('Big5Casino')
BOOKS.add('Cashalot')
BOOKS.add('RocketPlay')
BOOKS.add('Silverplay')
BOOKS.add('BetPremium')
BOOKS.add('Elitebet Australia')
BOOKS.add('Prewin')
BOOKS.add('Timberazo')
BOOKS.add('JeffBet')
BOOKS.add('Wintopia')
BOOKS.add('SlotsPalace')
BOOKS.add('31bet')
BOOKS.add('MarjoSports')
BOOKS.add('ZanziBet')
BOOKS.add('3et')
BOOKS.add('BetTarget')
BOOKS.add('Gomblingo')
BOOKS.add('Luckybet')
BOOKS.add('SBOTOP')
BOOKS.add('DinamoBet')
BOOKS.add('Pledoo')
BOOKS.add('BetX')
BOOKS.add('Gioca Sempre')
BOOKS.add('GREATwin')
BOOKS.add('Betzone')
BOOKS.add('Sekabet')
BOOKS.add('21bets.io')
BOOKS.add('Cryptorush')
BOOKS.add('Divas Casino')
BOOKS.add('Evobet')
BOOKS.add('Hyper Casino')
BOOKS.add('Uzbekbet')
BOOKS.add('WinPrincess')
BOOKS.add('24CasinoBet')
BOOKS.add('SixDot')
BOOKS.add('iJuego')
BOOKS.add('PlayZilla')
BOOKS.add('Coinplay')
BOOKS.add('Betfive')
BOOKS.add('Cazimbo')
BOOKS.add('Sportcash')
BOOKS.add('Wolf.bet')
BOOKS.add('Casino Sieger')
BOOKS.add('Fun88')
BOOKS.add('Hugewin')
BOOKS.add('Hopa')
BOOKS.add('Zenit Bet')
BOOKS.add('JVSpinbet')
BOOKS.add('Spinrollz')
BOOKS.add('Colossus Bets')
BOOKS.add('ebingo')
BOOKS.add('Pointsbet')
BOOKS.add('Suprabets')
BOOKS.add('Betinia')
BOOKS.add('Copa Gol')
BOOKS.add('Xlivebet')
BOOKS.add('Bet442')
BOOKS.add('Andromeda Bet')
BOOKS.add('Arcanebet')
BOOKS.add('Monster Casino')
BOOKS.add('BetSala')
BOOKS.add('Sgcasino')
BOOKS.add('WeltBet')
BOOKS.add('DolfWin')
BOOKS.add('Atmbet')
BOOKS.add('Kingmaker')
BOOKS.add('KonfamBet')
BOOKS.add('Solisbet')
BOOKS.add('Luckster')
BOOKS.add('BET-IBC')
BOOKS.add('TwinsBet')
BOOKS.add('Bookielink')
BOOKS.add('GuineeGames')
BOOKS.add('Hard Rock Sportsbook')
BOOKS.add('Casobet')
BOOKS.add('Betrino')
BOOKS.add('WinWinBet')
BOOKS.add('VertBet')
BOOKS.add('Fan-sport')
BOOKS.add('Golden Star Sport')
BOOKS.add('BahseGel')
BOOKS.add('Powbet')
BOOKS.add('Red Dice')
BOOKS.add('Playio')
BOOKS.add('SpinzWin')
BOOKS.add('Flappy Casino')
BOOKS.add('Bankonbet')
BOOKS.add('Betsport24')
BOOKS.add('Betssen')
BOOKS.add('Indibet')
BOOKS.add('PalmSlots')
BOOKS.add('TAB Online')
BOOKS.add('Barstool Sportsbook')
BOOKS.add('1957bet')
BOOKS.add('Gooooal Caipiao')
BOOKS.add('Casinobit')
BOOKS.add('Sultanbet')
BOOKS.add('Pálpitos')
BOOKS.add('WinnersBet')
BOOKS.add('Betman')
BOOKS.add('GoldenVegas')
BOOKS.add('Bumbet')
BOOKS.add('BetGlobal')
BOOKS.add('Tornadobet')
BOOKS.add('VegasMobileCasino')
BOOKS.add('Superbahis')
BOOKS.add('Baumbet')
BOOKS.add('Wallacebet')
BOOKS.add('Extra Game')
BOOKS.add('BetStorm')
BOOKS.add('SportsBroker')
BOOKS.add('Toto.ee')
BOOKS.add('EmirBet')
BOOKS.add('18bet')
BOOKS.add('Betgrouse')
BOOKS.add('b-Bets')
BOOKS.add('Feelingbet')
BOOKS.add('NorthStarBets')
BOOKS.add('Greyhound Channel')
BOOKS.add('Bahigo')
BOOKS.add('SportChamps')
BOOKS.add('Gamebookers')
BOOKS.add('Betnuvo')
BOOKS.add('puntoscommesse')
BOOKS.add('Wazobet')
BOOKS.add('Chacha.bet')
BOOKS.add('Legiano')
BOOKS.add('WePlayers')
BOOKS.add('Betcoco')
BOOKS.add('Zetbet')
BOOKS.add('Roby Casino')
BOOKS.add('Zotabet')
BOOKS.add('BFB247')
BOOKS.add('Elite Sportsbook')
BOOKS.add('Fullslot')
BOOKS.add('Jetwin')
BOOKS.add('LSbet')
BOOKS.add('Paridirect')
BOOKS.add('Asianodds')
BOOKS.add('Bettilt')
BOOKS.add('Pointbet')
BOOKS.add('Titanbet')
BOOKS.add('MobileWins')
BOOKS.add('LibraBet')
BOOKS.add('Vegazcasino')
BOOKS.add('Empirecitybets')
BOOKS.add('Bluefox Casino')
BOOKS.add('Playbet')
BOOKS.add('Casino Infinity')
BOOKS.add('Cyber.bet')
BOOKS.add('BetCup')
BOOKS.add('betcart')
BOOKS.add('Blackjack.fun')
BOOKS.add('Hexabet')
BOOKS.add('Eventogioco')
BOOKS.add('Spinbetter')
BOOKS.add('Kryptosino')
BOOKS.add('Pulibet')
BOOKS.add('Chasebet')
BOOKS.add('VOdds')
BOOKS.add('Alphabook')
BOOKS.add('Nashbet')
BOOKS.add('OhMySpins')
BOOKS.add('BetPark')
BOOKS.add('7bets')
BOOKS.add('Bettime')
BOOKS.add('Imajbet')
BOOKS.add('Crashino')
BOOKS.add('SaratogaBets')
BOOKS.add('Backhouse bet')
BOOKS.add('Action247')
BOOKS.add('V9BET')
BOOKS.add('Apostaquente')
BOOKS.add('10CRIC')
BOOKS.add('123bet')
BOOKS.add('Rembrandt')
BOOKS.add('88Bet')
BOOKS.add('Mostbet')
BOOKS.add('Betflip')
BOOKS.add('Dazzle Casino')
BOOKS.add('21bets')
BOOKS.add('Betsamigo')
BOOKS.add('RakeBit')
BOOKS.add('Giocagile')
BOOKS.add('PoleStar Casino')
BOOKS.add('RedStar')
BOOKS.add('VIP-IBC')
BOOKS.add('Galaxy.bet')
BOOKS.add('Wanabet')
BOOKS.add('K9Win')
BOOKS.add('BizBet')
BOOKS.add('Tempobet')
BOOKS.add('Sansabet')
BOOKS.add('Bet90')
BOOKS.add('Totowinners')
BOOKS.add('Vegasland')
BOOKS.add('NAB Casino')
BOOKS.add('Racecards.bet')
BOOKS.add('VenetianBet')
BOOKS.add('CasinoMega')
BOOKS.add('Betroller')
BOOKS.add('Bet2fun')
BOOKS.add('Brokerstorm')
BOOKS.add('Yonibet')
BOOKS.add('GunsBet')
BOOKS.add('Bola88')
BOOKS.add('Bet678')
BOOKS.add('Oppa888')
BOOKS.add('Parasino')
BOOKS.add('SimplesBet')
BOOKS.add('Joygames')
BOOKS.add('Nextbet')
BOOKS.add('Ole7.io')
BOOKS.add('Pin-up')
BOOKS.add('Treasurespins')
BOOKS.add('betkwiff')
BOOKS.add('SkillBet')
BOOKS.add('Hot.bet')
BOOKS.add('HallaBet')
BOOKS.add('Ditobet')
BOOKS.add('1GO')
BOOKS.add('Truenorth.bet')
BOOKS.add('Bitdreams')
BOOKS.add('BetSports')
BOOKS.add('Dude bet')
BOOKS.add('Mondobets')
BOOKS.add('Mazaplay')
BOOKS.add('DoubleBet')
BOOKS.add('Flipwager')
BOOKS.add('MercuryBet')
BOOKS.add('Olympusbet')
BOOKS.add('Betstro')
BOOKS.add('Interbet')
BOOKS.add('21LuckyBet')
BOOKS.add('Kikobet')
BOOKS.add('Globalbet')
BOOKS.add('Bets24')
BOOKS.add('CMD368')
BOOKS.add('OC88')
BOOKS.add('Betist')
BOOKS.add('Greatodds')
BOOKS.add('ItaliaCash')
BOOKS.add('Cryptobetsports')
BOOKS.add('SchnellWetten')
BOOKS.add('Vevobahis')
BOOKS.add('VIE')
BOOKS.add('Betify')
BOOKS.add('BetSofa')
BOOKS.add('Hititbet')
BOOKS.add('Jupi casino')
BOOKS.add('GG Gaming')
BOOKS.add('Grandwin')
BOOKS.add('Mediabet')
BOOKS.add('Derby Jackpot')
BOOKS.add('Jw8')
BOOKS.add('Finger Lakes Bonus Bet')
BOOKS.add('Estelarbet')
BOOKS.add('bet.me')
BOOKS.add('Bets10')
BOOKS.add('Bitubet')
BOOKS.add('Tipobet365')
BOOKS.add('Betboro')
BOOKS.add('InterBahis')
BOOKS.add('Best Bookies')
BOOKS.add('Bola228')
BOOKS.add('SlottoJam')
BOOKS.add('24Bettle')
BOOKS.add('Betlinee')
BOOKS.add('Kladionice Olimp')
BOOKS.add('888Bet Zambia')
BOOKS.add('Manny Bernstein')
BOOKS.add('Betland')
BOOKS.add('Go2Win')
BOOKS.add('AbaBet')
BOOKS.add('AlienBet')
BOOKS.add('Futureplay')
BOOKS.add('GWbet')
BOOKS.add('Supacasino')
BOOKS.add('Bahisbey')
BOOKS.add('Spinamba')
BOOKS.add('9Club')
BOOKS.add('MrXbet')
BOOKS.add('Sports.net')
BOOKS.add('4Kasino')
BOOKS.add('Eastbridge')
BOOKS.add('Win.city')
BOOKS.add('OdeonBet')
BOOKS.add('Wintop.io')
BOOKS.add('BetReg')
BOOKS.add('Winxbet')
BOOKS.add('redbet')
BOOKS.add('Dachbet')
BOOKS.add('Betador')
BOOKS.add('bettogoal')
BOOKS.add('BabiBet')
BOOKS.add('ejjaBET')
BOOKS.add('Astekbet')
BOOKS.add('betgo')
BOOKS.add('Savoy Betting')
BOOKS.add('J9')
BOOKS.add('RedAxePlay')
BOOKS.add('FoggyBet')
BOOKS.add('CompuBet')
BOOKS.add('OriginalBet')
BOOKS.add('link2bet')
BOOKS.add('BarrièreBet')
BOOKS.add('Bet-nox')
BOOKS.add('Kineko')
BOOKS.add('kisma')
BOOKS.add('Pokerblu')
BOOKS.add('Easysportbet')
BOOKS.add('Svenbet')
BOOKS.add('Vuoi Scommettere')
BOOKS.add('Wettigo')
BOOKS.add('Winscore')
BOOKS.add('Ganabet')
BOOKS.add('Betlily')
BOOKS.add('Letou')
BOOKS.add('VegasParadise')
BOOKS.add('Bet It All')
BOOKS.add('BetPas')
BOOKS.add('Edicolagames')
BOOKS.add('Betroad')
BOOKS.add('CasinoWinner')
BOOKS.add('Dozenspins')
BOOKS.add('DuoBetz')
BOOKS.add('Gol + Pas')
BOOKS.add('Kingbetting')
BOOKS.add('RedMileBets')
BOOKS.add('PriveWin')
BOOKS.add('RoyalFortune')
BOOKS.add('Giobet')
BOOKS.add('MobilBahis')
BOOKS.add('Betasia')
BOOKS.add('GreenBet')
BOOKS.add('Goalbet')
BOOKS.add('Betx101')
BOOKS.add('Nucleonbet')
BOOKS.add('Sportimba')
BOOKS.add('VIP Betting')
BOOKS.add('855crown')
BOOKS.add('Action24')
BOOKS.add('Ole777')
BOOKS.add('Robet247')
BOOKS.add('Gogawi')
BOOKS.add('Ringobet')
BOOKS.add('FairPlay')
BOOKS.add('Gfbwin888')
BOOKS.add('SlottyWay')
BOOKS.add('Spinbookie')
BOOKS.add('Sportandgames')
BOOKS.add('Betmatch.it')
BOOKS.add('BigBet24')
BOOKS.add('Makrobet')
BOOKS.add('TigerBet')
BOOKS.add('Zulabet')
BOOKS.add('Slotamba')
BOOKS.add('Betmartini')
BOOKS.add('Lotos Wetten')
BOOKS.add('Wazamba')
BOOKS.add('ZeusWin')
BOOKS.add('20bets')
BOOKS.add('AFBCash')
BOOKS.add('Betreels')
